apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-kisjang
  labels:
    app: frontend-kisjang
spec:
  selector:
    matchLabels:
      app: frontend-kisjang
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-kisjang
    spec:
      containers:
        - name: frontend-kisjang
          image: nalleyda/frontend-kisjang
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
