apiVersion: v1
kind: Service
metadata:
  name: frontend-lab12 
  labels:
    name: frontend-lab12
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend-lab12
  type: NodePort
